### ISSUE TITLE
Ban risk on Hypixel

### ISSUE THREAD

**Issue by lunaynx** [FamroFexl/ViewLock#2]
The mod seems to automatically re-lock your view even if it is changed by an external force such as teleporting, which is risky for two reasons:

1. This behavior was explicitly listed as something that will trip Watchdog by an admin in [a forum post](https://hypixel.net/threads/regarding-the-recent-announcement-with-mods-in-skyblock.4045481/): "If you do something that changes where you're facing after you teleport, that's definitely gonna get flagged". It didn't seem to get me flagged so far, but I wouldn't risk continuing to use it as-is.
2. It will almost certainly get you banned if you have it on during a macro check, as some of Hypixel's macro checks work by rotating the player, and given the behavior with teleporting I'm willing to bet this mod would automatically rotate you back immediately.

**Comment by FamroFexl** [comment]
I can't realistically guarantee this mod will be server-safe. The server can detect this mod in many ways. 
1. The server can query a Fabric Mod List packet and check it against a mod list, which this mod might eventually end up on.
2. The anti-cheat might get suspicious when it sees the player performing mouse clicks without their view moving.
3. Snapping your view perfectly to an axis is very suspicious.

However, if all you're asking is to disable the mod when it detects a teleport, I might be able to do that.

**Comment by lunaynx** [comment]
> 1. The server can query a Fabric Mod List packet and check it against a mod list, which this mod might eventually end up on.

Isn't this only a thing with Forge? AFAIK Fabric doesn't send a mod list.

> 2. The anti-cheat might get suspicious when it sees the player performing mouse clicks without their view moving.

This is generally not an issue on Hypixel, they just do some random macro check challenges if you do it too long without breaks, which can easily be passed if you're paying at least a little attention to the screen and/or sounds.

> 3. Snapping your view perfectly to an axis is very suspicious.

Yeah I guess it could be, especially if it's suddenly snapped, though sometimes we need to get it close to perfect for efficient farming. Doesn't seem to be an issue so far.

> However, if all you're asking is to disable the mod when it detects a teleport, I might be able to do that.

Yeah, sounds good to disable it on teleport, and also if the server suddenly rotates the player without moving it (not sure if that counts as a teleport).

**Comment by FamroFexl** [comment]
> Isn't this only a thing with Forge? AFAIK Fabric doesn't send a mod list.
>
No, Fabric sends a mod list on request so it can ensure version and mod compatibility between the client and the server. Hypixel could easily theoretically imitate a Forge or Fabric server and ask for that packet if the client is branded as a fabric or forge client. I do know of hacked clients/mods that can imitate a vanilla client to disable this vulnerability.

Out of curiosity, are you using the Fabric version of the mod or the Forge 1.8.9 version. I heard you mention farming so I assume you use Fabric based on how Hypixel requires newer versions for certain gamemodes.

**Comment by lunaynx** [comment]
I do know Hypixel prevents you from joining with certain Forge mods, but I never heard of Fabric having anything like this and never had them complain about any mod I had.

I'm using the Fabric version on 1.20.2 because I'm weird like that. :P SkyBlock currently supports 1.8.9 for everything including farming and is the go-to version for most players, I just can't stand it despite that version having so many good Forge mods for SkyBlock, I rather use 1.20.2 with Skyblocker and help port over missing features myself.

**Comment by BasiqueEvangelist** [comment]
> No, Fabric sends a mod list on request so it can ensure version and mod compatibility between the client and the server.

No?
The only thing Fabric really does is set the client brand to `fabric` and send over registered network channels to the server. The only packet that guarantees mod compatibility is registry sync, which is sent by the server and isn't used if you didn't register anything.

**Comment by FamroFexl** [comment]
@BasiqueEvangelist That might be true. Disregard my previous statement; I previously worked mostly with Forge.

**Comment by FamroFexl** [comment]
When the player is teleported (their view is rotated or they are moved, same packet), the view lock will disable and a message will popup in chat. Click the message to restore your view state after it was disabled or alternatively, type the command "/vl relock". 

A two-tick cool-down to the teleport packet listener was added after multiple "Player moved too quickly!" server messages spammed the player chat with the same view lock restore request.

**Comment by FamroFexl** [comment]
This has changed in version 1.1.2 (see [here](https://github.com/FamroFexl/ViewLock/releases/tag/v1.1.2)). 

Now, the view is unlocked with "/vl unlock" and relocked (locks restored) with "/vl relock". This allows you to save your current lock state until you need it again.
