### ISSUE TITLE
[Feature request]: lock view towards coordinate

### ISSUE THREAD

**Issue by zachman42** [FamroFexl/ViewLock#4]
### Suggestion

Something that I've needed before is the ability to face directly towards a certain block so that way I can build in a straight line towards it. 
This can easily be done by taking block coordinates input through the /vl command, and then calculating and locking to the angles that face directly towards that block using the players exact coordinates. 
Granted this can be done manually by the user, but it would be much more efficient if it was built in.

**Comment by FamroFexl** [comment]
So specifically, your asking for a command to align the player's view to the center of the block their crosshair is pointed at, correct?

**Comment by zachman42** [comment]
I was thinking adding an option to the view lock command where you actually enter the coordinates. That way you can enter coordinates with much more precision. (for example, I'm currently connecting portals on the nether roof with a line of torches between them, so I need to be locked on in between the two portal blocks instead of the center of one of them). Also it would prevent you from being unable to lock on to a block outside of the player's render distance.

**Comment by FamroFexl** [comment]
The feature has been implemented and will be available in the next fabric release

**Comment by FamroFexl** [comment]
@zachman42 View [this release](https://github.com/FamroFexl/ViewLock/releases/tag/v1.2) for full information. For your use case, I would recommend using `/vl block view` to track to your requested block and then using `/vl block ~ ~ ~ track` to relatively position it to a specific section of that block. The `track` argument allows you to move around while keeping your view on the block, however it is limited by the minecraft tick rate (20tps), so it will stutter at close distances.
